<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260525213852 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE goodie_categories (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, name VARCHAR(128) NOT NULL, description TEXT DEFAULT NULL, is_active BOOLEAN NOT NULL, display_order INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A55C7A5BD17F50A6 ON goodie_categories (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A55C7A5B5E237E06 ON goodie_categories (name)');
        $this->addSql('CREATE TABLE goodie_distributions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, item_name VARCHAR(128) NOT NULL, quantity INT NOT NULL, hours_at_distribution DOUBLE PRECISION NOT NULL, distributed_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, notes TEXT DEFAULT NULL, user_id INT NOT NULL, item_id INT DEFAULT NULL, distributed_by INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_92A2A85AA76ED395 ON goodie_distributions (user_id)');
        $this->addSql('CREATE INDEX IDX_92A2A85A126F525E ON goodie_distributions (item_id)');
        $this->addSql('CREATE INDEX IDX_92A2A85A92B69FA8 ON goodie_distributions (distributed_by)');
        $this->addSql('CREATE TABLE goodie_items (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, name VARCHAR(128) NOT NULL, description TEXT DEFAULT NULL, required_hours DOUBLE PRECISION NOT NULL, max_per_person INT DEFAULT NULL, is_active BOOLEAN NOT NULL, display_order INT NOT NULL, category_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_99ED2E3D17F50A6 ON goodie_items (uuid)');
        $this->addSql('CREATE INDEX IDX_99ED2E312469DE2 ON goodie_items (category_id)');
        $this->addSql('CREATE TABLE user_hours_cache (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, total_hours DOUBLE PRECISION NOT NULL, day_shifts_hours DOUBLE PRECISION NOT NULL, night_shifts_hours DOUBLE PRECISION NOT NULL, noshow_penalty_hours DOUBLE PRECISION NOT NULL, worklog_hours DOUBLE PRECISION NOT NULL, completed_shifts_count INT NOT NULL, night_shifts_count INT NOT NULL, noshow_shifts_count INT NOT NULL, last_calculated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FB1BACE0A76ED395 ON user_hours_cache (user_id)');
        $this->addSql('ALTER TABLE goodie_distributions ADD CONSTRAINT FK_92A2A85AA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE goodie_distributions ADD CONSTRAINT FK_92A2A85A126F525E FOREIGN KEY (item_id) REFERENCES goodie_items (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE goodie_distributions ADD CONSTRAINT FK_92A2A85A92B69FA8 FOREIGN KEY (distributed_by) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE goodie_items ADD CONSTRAINT FK_99ED2E312469DE2 FOREIGN KEY (category_id) REFERENCES goodie_categories (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_hours_cache ADD CONSTRAINT FK_FB1BACE0A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE goodie_distributions DROP CONSTRAINT FK_92A2A85AA76ED395');
        $this->addSql('ALTER TABLE goodie_distributions DROP CONSTRAINT FK_92A2A85A126F525E');
        $this->addSql('ALTER TABLE goodie_distributions DROP CONSTRAINT FK_92A2A85A92B69FA8');
        $this->addSql('ALTER TABLE goodie_items DROP CONSTRAINT FK_99ED2E312469DE2');
        $this->addSql('ALTER TABLE user_hours_cache DROP CONSTRAINT FK_FB1BACE0A76ED395');
        $this->addSql('DROP TABLE goodie_categories');
        $this->addSql('DROP TABLE goodie_distributions');
        $this->addSql('DROP TABLE goodie_items');
        $this->addSql('DROP TABLE user_hours_cache');
    }
}
