<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260728160000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Track failed password logins and the brute-force timeouts they trigger';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE login_attempts (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username_key VARCHAR(180) NOT NULL, ip_hash VARCHAR(64) NOT NULL, attempted_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_login_attempt_username ON login_attempts (username_key, attempted_at)');
        $this->addSql('CREATE INDEX idx_login_attempt_ip ON login_attempts (ip_hash, attempted_at)');

        $this->addSql('CREATE TABLE login_lockouts (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, scope VARCHAR(16) NOT NULL, subject VARCHAR(180) NOT NULL, locked_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, locked_until TIMESTAMP(0) WITH TIME ZONE NOT NULL, failure_count INT NOT NULL, source_count INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_629E9C3CD17F50A6 ON login_lockouts (uuid)');
        // The throttle upserts on this constraint (INSERT ... ON CONFLICT), so it settles the race
        // between two failed logins that cross the threshold at the same moment. Dropping it would
        // turn that race back into a unique violation, which closes the EntityManager mid-login.
        $this->addSql('CREATE UNIQUE INDEX uniq_login_lockout_subject ON login_lockouts (scope, subject)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE login_lockouts');
        $this->addSql('DROP TABLE login_attempts');
    }
}
