<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260712101139 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Global Planning Availability: planning_availabilities header + availability_ranges.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE availability_ranges (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, starts_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, ends_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, value VARCHAR(16) NOT NULL, availability_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_65E8E5B961778466 ON availability_ranges (availability_id)');
        $this->addSql('CREATE INDEX idx_avail_range_span ON availability_ranges (starts_at, ends_at)');
        $this->addSql('CREATE TABLE planning_availabilities (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, comment TEXT DEFAULT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D3D77A93A76ED395 ON planning_availabilities (user_id)');
        $this->addSql('ALTER TABLE availability_ranges ADD CONSTRAINT FK_65E8E5B961778466 FOREIGN KEY (availability_id) REFERENCES planning_availabilities (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE planning_availabilities ADD CONSTRAINT FK_D3D77A93A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE availability_ranges DROP CONSTRAINT FK_65E8E5B961778466');
        $this->addSql('ALTER TABLE planning_availabilities DROP CONSTRAINT FK_D3D77A93A76ED395');
        $this->addSql('DROP TABLE availability_ranges');
        $this->addSql('DROP TABLE planning_availabilities');
    }
}
