<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260711224200 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Delegated manager requests';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE delegated_manager_requests (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(16) NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, decided_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, department_id INT NOT NULL, subject_id INT NOT NULL, requested_by_id INT DEFAULT NULL, decided_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6833FE11AE80F5DF ON delegated_manager_requests (department_id)');
        $this->addSql('CREATE INDEX IDX_6833FE1123EDC87 ON delegated_manager_requests (subject_id)');
        $this->addSql('CREATE INDEX IDX_6833FE114DA1E751 ON delegated_manager_requests (requested_by_id)');
        $this->addSql('CREATE INDEX IDX_6833FE11E26B496B ON delegated_manager_requests (decided_by_id)');
        $this->addSql('ALTER TABLE delegated_manager_requests ADD CONSTRAINT FK_6833FE11AE80F5DF FOREIGN KEY (department_id) REFERENCES departments (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE delegated_manager_requests ADD CONSTRAINT FK_6833FE1123EDC87 FOREIGN KEY (subject_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE delegated_manager_requests ADD CONSTRAINT FK_6833FE114DA1E751 FOREIGN KEY (requested_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE delegated_manager_requests ADD CONSTRAINT FK_6833FE11E26B496B FOREIGN KEY (decided_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE delegated_manager_requests DROP CONSTRAINT FK_6833FE11AE80F5DF');
        $this->addSql('ALTER TABLE delegated_manager_requests DROP CONSTRAINT FK_6833FE1123EDC87');
        $this->addSql('ALTER TABLE delegated_manager_requests DROP CONSTRAINT FK_6833FE114DA1E751');
        $this->addSql('ALTER TABLE delegated_manager_requests DROP CONSTRAINT FK_6833FE11E26B496B');
        $this->addSql('DROP TABLE delegated_manager_requests');
    }
}
