<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260712120817 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Conversation model: conversations, conversation_participants, chat_messages.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE chat_messages (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT DEFAULT NULL, image_path VARCHAR(255) DEFAULT NULL, internal BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, edited_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, conversation_id INT NOT NULL, sender_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EF20C9A69AC0396 ON chat_messages (conversation_id)');
        $this->addSql('CREATE INDEX IDX_EF20C9A6F624B39D ON chat_messages (sender_id)');
        $this->addSql('CREATE TABLE conversation_participants (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, last_read_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, conversation_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_21821ED39AC0396 ON conversation_participants (conversation_id)');
        $this->addSql('CREATE INDEX IDX_21821ED3A76ED395 ON conversation_participants (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_conv_user ON conversation_participants (conversation_id, user_id)');
        $this->addSql('CREATE TABLE conversations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(16) NOT NULL, status VARCHAR(16) NOT NULL, claimed_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, exclusive_claim BOOLEAN NOT NULL, version INT DEFAULT 1 NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, subject_id INT DEFAULT NULL, claimed_by INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C2521BF123EDC87 ON conversations (subject_id)');
        $this->addSql('CREATE INDEX IDX_C2521BF1296C217B ON conversations (claimed_by)');
        $this->addSql('ALTER TABLE chat_messages ADD CONSTRAINT FK_EF20C9A69AC0396 FOREIGN KEY (conversation_id) REFERENCES conversations (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE chat_messages ADD CONSTRAINT FK_EF20C9A6F624B39D FOREIGN KEY (sender_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE conversation_participants ADD CONSTRAINT FK_21821ED39AC0396 FOREIGN KEY (conversation_id) REFERENCES conversations (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE conversation_participants ADD CONSTRAINT FK_21821ED3A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE conversations ADD CONSTRAINT FK_C2521BF123EDC87 FOREIGN KEY (subject_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE conversations ADD CONSTRAINT FK_C2521BF1296C217B FOREIGN KEY (claimed_by) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE chat_messages DROP CONSTRAINT FK_EF20C9A69AC0396');
        $this->addSql('ALTER TABLE chat_messages DROP CONSTRAINT FK_EF20C9A6F624B39D');
        $this->addSql('ALTER TABLE conversation_participants DROP CONSTRAINT FK_21821ED39AC0396');
        $this->addSql('ALTER TABLE conversation_participants DROP CONSTRAINT FK_21821ED3A76ED395');
        $this->addSql('ALTER TABLE conversations DROP CONSTRAINT FK_C2521BF123EDC87');
        $this->addSql('ALTER TABLE conversations DROP CONSTRAINT FK_C2521BF1296C217B');
        $this->addSql('DROP TABLE chat_messages');
        $this->addSql('DROP TABLE conversation_participants');
        $this->addSql('DROP TABLE conversations');
    }
}
