<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260526053506 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE certification_tokens (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token VARCHAR(64) NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, certification_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4C7208395F37A13B ON certification_tokens (token)');
        $this->addSql('CREATE INDEX IDX_4C720839CB47068A ON certification_tokens (certification_id)');
        $this->addSql('CREATE TABLE digital_id_tokens (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token VARCHAR(64) NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_678367375F37A13B ON digital_id_tokens (token)');
        $this->addSql('CREATE INDEX IDX_67836737A76ED395 ON digital_id_tokens (user_id)');
        $this->addSql('CREATE TABLE user_certifications (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(32) NOT NULL, date_certified TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, date_expires TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, user_id INT NOT NULL, certification_id INT NOT NULL, certified_by INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5088A98CA76ED395 ON user_certifications (user_id)');
        $this->addSql('CREATE INDEX IDX_5088A98CCB47068A ON user_certifications (certification_id)');
        $this->addSql('CREATE INDEX IDX_5088A98CAE342815 ON user_certifications (certified_by)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_certification ON user_certifications (user_id, certification_id)');
        $this->addSql('ALTER TABLE certification_tokens ADD CONSTRAINT FK_4C720839CB47068A FOREIGN KEY (certification_id) REFERENCES certifications (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE digital_id_tokens ADD CONSTRAINT FK_67836737A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_certifications ADD CONSTRAINT FK_5088A98CA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_certifications ADD CONSTRAINT FK_5088A98CCB47068A FOREIGN KEY (certification_id) REFERENCES certifications (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_certifications ADD CONSTRAINT FK_5088A98CAE342815 FOREIGN KEY (certified_by) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE certification_tokens DROP CONSTRAINT FK_4C720839CB47068A');
        $this->addSql('ALTER TABLE digital_id_tokens DROP CONSTRAINT FK_67836737A76ED395');
        $this->addSql('ALTER TABLE user_certifications DROP CONSTRAINT FK_5088A98CA76ED395');
        $this->addSql('ALTER TABLE user_certifications DROP CONSTRAINT FK_5088A98CCB47068A');
        $this->addSql('ALTER TABLE user_certifications DROP CONSTRAINT FK_5088A98CAE342815');
        $this->addSql('DROP TABLE certification_tokens');
        $this->addSql('DROP TABLE digital_id_tokens');
        $this->addSql('DROP TABLE user_certifications');
    }
}
