<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260711203341 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Notifications, notification preferences, reminder-lead setting';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE notification_preferences (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, category VARCHAR(48) NOT NULL, in_app BOOLEAN NOT NULL, email BOOLEAN NOT NULL, telegram BOOLEAN NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3CAA95B4A76ED395 ON notification_preferences (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_notif_pref_user_category ON notification_preferences (user_id, category)');
        $this->addSql('CREATE TABLE notifications (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, category VARCHAR(48) NOT NULL, title VARCHAR(255) NOT NULL, message TEXT NOT NULL, action_url VARCHAR(512) DEFAULT NULL, mandatory BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, read_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6000B0D3A76ED395 ON notifications (user_id)');
        $this->addSql('CREATE INDEX idx_notification_user_read ON notifications (user_id, read_at)');
        $this->addSql('ALTER TABLE notification_preferences ADD CONSTRAINT FK_3CAA95B4A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D3A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE users_settings ADD notification_reminder_lead INT DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE notification_preferences DROP CONSTRAINT FK_3CAA95B4A76ED395');
        $this->addSql('ALTER TABLE notifications DROP CONSTRAINT FK_6000B0D3A76ED395');
        $this->addSql('DROP TABLE notification_preferences');
        $this->addSql('DROP TABLE notifications');
        $this->addSql('ALTER TABLE users_settings DROP notification_reminder_lead');
    }
}
