<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260627110305 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Badges, user-badge join and account invite tokens';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE badges (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(64) NOT NULL, slug VARCHAR(64) NOT NULL, type VARCHAR(16) NOT NULL, priority INT NOT NULL, color VARCHAR(32) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_78F6539A5E237E06 ON badges (name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_78F6539A989D9B62 ON badges (slug)');
        $this->addSql('CREATE TABLE invite_tokens (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token VARCHAR(64) NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_87558B5D5F37A13B ON invite_tokens (token)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_87558B5DA76ED395 ON invite_tokens (user_id)');
        $this->addSql('CREATE TABLE users_badges (user_id INT NOT NULL, badge_id INT NOT NULL, PRIMARY KEY (user_id, badge_id))');
        $this->addSql('CREATE INDEX IDX_7711DD0AA76ED395 ON users_badges (user_id)');
        $this->addSql('CREATE INDEX IDX_7711DD0AF7A2C2FC ON users_badges (badge_id)');
        $this->addSql('ALTER TABLE invite_tokens ADD CONSTRAINT FK_87558B5DA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE users_badges ADD CONSTRAINT FK_7711DD0AA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE users_badges ADD CONSTRAINT FK_7711DD0AF7A2C2FC FOREIGN KEY (badge_id) REFERENCES badges (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE invite_tokens DROP CONSTRAINT FK_87558B5DA76ED395');
        $this->addSql('ALTER TABLE users_badges DROP CONSTRAINT FK_7711DD0AA76ED395');
        $this->addSql('ALTER TABLE users_badges DROP CONSTRAINT FK_7711DD0AF7A2C2FC');
        $this->addSql('DROP TABLE badges');
        $this->addSql('DROP TABLE invite_tokens');
        $this->addSql('DROP TABLE users_badges');
    }
}
