<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260525201954 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE groups (id INT NOT NULL, name VARCHAR(64) NOT NULL, slug VARCHAR(64) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F06D39705E237E06 ON groups (name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F06D3970989D9B62 ON groups (slug)');
        $this->addSql('CREATE TABLE group_privileges (group_id INT NOT NULL, privilege_id INT NOT NULL, PRIMARY KEY (group_id, privilege_id))');
        $this->addSql('CREATE INDEX IDX_BF9898A0FE54D947 ON group_privileges (group_id)');
        $this->addSql('CREATE INDEX IDX_BF9898A032FB8AEA ON group_privileges (privilege_id)');
        $this->addSql('CREATE TABLE password_resets (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token VARCHAR(32) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9EDAFEA15F37A13B ON password_resets (token)');
        $this->addSql('CREATE INDEX IDX_9EDAFEA1A76ED395 ON password_resets (user_id)');
        $this->addSql('CREATE TABLE privileges (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(128) NOT NULL, description VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6855F9125E237E06 ON privileges (name)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(24) NOT NULL, email VARCHAR(254) NOT NULL, password VARCHAR(255) NOT NULL, api_key VARCHAR(32) NOT NULL, last_login_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E95E237E06 ON users (name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9C912ED9D ON users (api_key)');
        $this->addSql('CREATE TABLE users_groups (user_id INT NOT NULL, group_id INT NOT NULL, PRIMARY KEY (user_id, group_id))');
        $this->addSql('CREATE INDEX IDX_FF8AB7E0A76ED395 ON users_groups (user_id)');
        $this->addSql('CREATE INDEX IDX_FF8AB7E0FE54D947 ON users_groups (group_id)');
        $this->addSql('CREATE TABLE users_contact (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, dect VARCHAR(5) DEFAULT NULL, mobile VARCHAR(40) DEFAULT NULL, email VARCHAR(254) DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BC6292F2A76ED395 ON users_contact (user_id)');
        $this->addSql('CREATE TABLE users_personal_data (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(64) DEFAULT NULL, last_name VARCHAR(64) DEFAULT NULL, pronoun VARCHAR(15) DEFAULT NULL, shirt_size VARCHAR(4) DEFAULT NULL, badge_number INT DEFAULT NULL, planned_arrival_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, planned_departure_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_951CFC53A76ED395 ON users_personal_data (user_id)');
        $this->addSql('CREATE TABLE users_settings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, language VARCHAR(10) NOT NULL, theme INT NOT NULL, email_human BOOLEAN NOT NULL, email_messages BOOLEAN NOT NULL, email_goodie BOOLEAN NOT NULL, email_shiftinfo BOOLEAN NOT NULL, email_news BOOLEAN NOT NULL, mobile_show BOOLEAN NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9E048B1FA76ED395 ON users_settings (user_id)');
        $this->addSql('CREATE TABLE users_state (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, arrived BOOLEAN NOT NULL, arrival_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_info TEXT DEFAULT NULL, active BOOLEAN NOT NULL, force_active BOOLEAN NOT NULL, got_goodie BOOLEAN NOT NULL, got_voucher INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_44E476B2A76ED395 ON users_state (user_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE group_privileges ADD CONSTRAINT FK_BF9898A0FE54D947 FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE group_privileges ADD CONSTRAINT FK_BF9898A032FB8AEA FOREIGN KEY (privilege_id) REFERENCES privileges (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE password_resets ADD CONSTRAINT FK_9EDAFEA1A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE users_groups ADD CONSTRAINT FK_FF8AB7E0A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE users_groups ADD CONSTRAINT FK_FF8AB7E0FE54D947 FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE users_contact ADD CONSTRAINT FK_BC6292F2A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE users_personal_data ADD CONSTRAINT FK_951CFC53A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE users_settings ADD CONSTRAINT FK_9E048B1FA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE users_state ADD CONSTRAINT FK_44E476B2A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE group_privileges DROP CONSTRAINT FK_BF9898A0FE54D947');
        $this->addSql('ALTER TABLE group_privileges DROP CONSTRAINT FK_BF9898A032FB8AEA');
        $this->addSql('ALTER TABLE password_resets DROP CONSTRAINT FK_9EDAFEA1A76ED395');
        $this->addSql('ALTER TABLE users_groups DROP CONSTRAINT FK_FF8AB7E0A76ED395');
        $this->addSql('ALTER TABLE users_groups DROP CONSTRAINT FK_FF8AB7E0FE54D947');
        $this->addSql('ALTER TABLE users_contact DROP CONSTRAINT FK_BC6292F2A76ED395');
        $this->addSql('ALTER TABLE users_personal_data DROP CONSTRAINT FK_951CFC53A76ED395');
        $this->addSql('ALTER TABLE users_settings DROP CONSTRAINT FK_9E048B1FA76ED395');
        $this->addSql('ALTER TABLE users_state DROP CONSTRAINT FK_44E476B2A76ED395');
        $this->addSql('DROP TABLE groups');
        $this->addSql('DROP TABLE group_privileges');
        $this->addSql('DROP TABLE password_resets');
        $this->addSql('DROP TABLE privileges');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE users_groups');
        $this->addSql('DROP TABLE users_contact');
        $this->addSql('DROP TABLE users_personal_data');
        $this->addSql('DROP TABLE users_settings');
        $this->addSql('DROP TABLE users_state');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
