<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260525220525 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE faqs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, category VARCHAR(128) NOT NULL, question TEXT NOT NULL, answer TEXT NOT NULL, display_order INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messages (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, text TEXT NOT NULL, is_read BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, sender_id INT NOT NULL, receiver_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DB021E96F624B39D ON messages (sender_id)');
        $this->addSql('CREATE INDEX IDX_DB021E96CD53EDB6 ON messages (receiver_id)');
        $this->addSql('CREATE INDEX idx_message_pair ON messages (sender_id, receiver_id)');
        $this->addSql('CREATE TABLE news (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, text TEXT NOT NULL, is_meeting BOOLEAN NOT NULL, is_pinned BOOLEAN NOT NULL, is_highlighted BOOLEAN NOT NULL, staff_only BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, author_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1DD39950F675F31B ON news (author_id)');
        $this->addSql('CREATE TABLE news_comments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, text TEXT NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, news_id INT NOT NULL, author_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_16A0357BB5A459A0 ON news_comments (news_id)');
        $this->addSql('CREATE INDEX IDX_16A0357BF675F31B ON news_comments (author_id)');
        $this->addSql('CREATE TABLE questions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, text TEXT NOT NULL, answer TEXT DEFAULT NULL, answered_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, locked_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, user_id INT DEFAULT NULL, answerer_id INT DEFAULT NULL, locked_by INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8ADC54D5A76ED395 ON questions (user_id)');
        $this->addSql('CREATE INDEX IDX_8ADC54D5CCC8E8CE ON questions (answerer_id)');
        $this->addSql('CREATE INDEX IDX_8ADC54D5719C4CB1 ON questions (locked_by)');
        $this->addSql('ALTER TABLE messages ADD CONSTRAINT FK_DB021E96F624B39D FOREIGN KEY (sender_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE messages ADD CONSTRAINT FK_DB021E96CD53EDB6 FOREIGN KEY (receiver_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE news ADD CONSTRAINT FK_1DD39950F675F31B FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE news_comments ADD CONSTRAINT FK_16A0357BB5A459A0 FOREIGN KEY (news_id) REFERENCES news (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE news_comments ADD CONSTRAINT FK_16A0357BF675F31B FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE questions ADD CONSTRAINT FK_8ADC54D5A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE questions ADD CONSTRAINT FK_8ADC54D5CCC8E8CE FOREIGN KEY (answerer_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE questions ADD CONSTRAINT FK_8ADC54D5719C4CB1 FOREIGN KEY (locked_by) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE messages DROP CONSTRAINT FK_DB021E96F624B39D');
        $this->addSql('ALTER TABLE messages DROP CONSTRAINT FK_DB021E96CD53EDB6');
        $this->addSql('ALTER TABLE news DROP CONSTRAINT FK_1DD39950F675F31B');
        $this->addSql('ALTER TABLE news_comments DROP CONSTRAINT FK_16A0357BB5A459A0');
        $this->addSql('ALTER TABLE news_comments DROP CONSTRAINT FK_16A0357BF675F31B');
        $this->addSql('ALTER TABLE questions DROP CONSTRAINT FK_8ADC54D5A76ED395');
        $this->addSql('ALTER TABLE questions DROP CONSTRAINT FK_8ADC54D5CCC8E8CE');
        $this->addSql('ALTER TABLE questions DROP CONSTRAINT FK_8ADC54D5719C4CB1');
        $this->addSql('DROP TABLE faqs');
        $this->addSql('DROP TABLE messages');
        $this->addSql('DROP TABLE news');
        $this->addSql('DROP TABLE news_comments');
        $this->addSql('DROP TABLE questions');
    }
}
