<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260712103633 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Automatic assignment proposals: assignment_proposals + proposal_assignments.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE assignment_proposals (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(16) NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, department_id INT NOT NULL, created_by INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_68A93E68AE80F5DF ON assignment_proposals (department_id)');
        $this->addSql('CREATE INDEX IDX_68A93E68DE12AB56 ON assignment_proposals (created_by)');
        $this->addSql('CREATE TABLE proposal_assignments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, availability_value VARCHAR(16) DEFAULT NULL, proposal_id INT NOT NULL, shift_id INT NOT NULL, user_id INT NOT NULL, volunteer_type_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_899EB6E7F4792058 ON proposal_assignments (proposal_id)');
        $this->addSql('CREATE INDEX IDX_899EB6E7BB70BC0E ON proposal_assignments (shift_id)');
        $this->addSql('CREATE INDEX IDX_899EB6E7A76ED395 ON proposal_assignments (user_id)');
        $this->addSql('CREATE INDEX IDX_899EB6E71BA493AB ON proposal_assignments (volunteer_type_id)');
        $this->addSql('ALTER TABLE assignment_proposals ADD CONSTRAINT FK_68A93E68AE80F5DF FOREIGN KEY (department_id) REFERENCES departments (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE assignment_proposals ADD CONSTRAINT FK_68A93E68DE12AB56 FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE proposal_assignments ADD CONSTRAINT FK_899EB6E7F4792058 FOREIGN KEY (proposal_id) REFERENCES assignment_proposals (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE proposal_assignments ADD CONSTRAINT FK_899EB6E7BB70BC0E FOREIGN KEY (shift_id) REFERENCES shifts (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE proposal_assignments ADD CONSTRAINT FK_899EB6E7A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE proposal_assignments ADD CONSTRAINT FK_899EB6E71BA493AB FOREIGN KEY (volunteer_type_id) REFERENCES volunteer_types (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE assignment_proposals DROP CONSTRAINT FK_68A93E68AE80F5DF');
        $this->addSql('ALTER TABLE assignment_proposals DROP CONSTRAINT FK_68A93E68DE12AB56');
        $this->addSql('ALTER TABLE proposal_assignments DROP CONSTRAINT FK_899EB6E7F4792058');
        $this->addSql('ALTER TABLE proposal_assignments DROP CONSTRAINT FK_899EB6E7BB70BC0E');
        $this->addSql('ALTER TABLE proposal_assignments DROP CONSTRAINT FK_899EB6E7A76ED395');
        $this->addSql('ALTER TABLE proposal_assignments DROP CONSTRAINT FK_899EB6E71BA493AB');
        $this->addSql('DROP TABLE assignment_proposals');
        $this->addSql('DROP TABLE proposal_assignments');
    }
}
