<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260711195926 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Operational status overrides (Free to help)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE operational_status_overrides (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value VARCHAR(32) NOT NULL, expires_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1983643FA76ED395 ON operational_status_overrides (user_id)');
        $this->addSql('ALTER TABLE operational_status_overrides ADD CONSTRAINT FK_1983643FA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE operational_status_overrides DROP CONSTRAINT FK_1983643FA76ED395');
        $this->addSql('DROP TABLE operational_status_overrides');
    }
}
