<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260627120521 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Telegram link requests, configuration and user Telegram fields';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE telegram_configuration (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, enabled BOOLEAN NOT NULL, api_endpoint VARCHAR(255) NOT NULL, api_key TEXT DEFAULT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE telegram_link_requests (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(32) NOT NULL, status VARCHAR(16) NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, confirmed_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F20D4D177153098 ON telegram_link_requests (code)');
        $this->addSql('CREATE INDEX IDX_F20D4D1A76ED395 ON telegram_link_requests (user_id)');
        $this->addSql('ALTER TABLE telegram_link_requests ADD CONSTRAINT FK_F20D4D1A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE users ADD telegram_id VARCHAR(64) DEFAULT NULL');
        $this->addSql('ALTER TABLE users ADD telegram_handle VARCHAR(64) DEFAULT NULL');
        $this->addSql('ALTER TABLE users ADD telegram_linked_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE telegram_link_requests DROP CONSTRAINT FK_F20D4D1A76ED395');
        $this->addSql('DROP TABLE telegram_configuration');
        $this->addSql('DROP TABLE telegram_link_requests');
        $this->addSql('ALTER TABLE users DROP telegram_id');
        $this->addSql('ALTER TABLE users DROP telegram_handle');
        $this->addSql('ALTER TABLE users DROP telegram_linked_at');
    }
}
