<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260711225435 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Volunteer type department_only, certifications, contacts';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE volunteer_type_contacts (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(128) DEFAULT NULL, phone VARCHAR(40) DEFAULT NULL, telegram VARCHAR(64) DEFAULT NULL, email VARCHAR(254) DEFAULT NULL, volunteer_type_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_60FAC6F11BA493AB ON volunteer_type_contacts (volunteer_type_id)');
        $this->addSql('CREATE TABLE volunteer_type_certifications (volunteer_type_id INT NOT NULL, certification_id INT NOT NULL, PRIMARY KEY (volunteer_type_id, certification_id))');
        $this->addSql('CREATE INDEX IDX_BA15F8981BA493AB ON volunteer_type_certifications (volunteer_type_id)');
        $this->addSql('CREATE INDEX IDX_BA15F898CB47068A ON volunteer_type_certifications (certification_id)');
        $this->addSql('ALTER TABLE volunteer_type_contacts ADD CONSTRAINT FK_60FAC6F11BA493AB FOREIGN KEY (volunteer_type_id) REFERENCES volunteer_types (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE volunteer_type_certifications ADD CONSTRAINT FK_BA15F8981BA493AB FOREIGN KEY (volunteer_type_id) REFERENCES volunteer_types (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE volunteer_type_certifications ADD CONSTRAINT FK_BA15F898CB47068A FOREIGN KEY (certification_id) REFERENCES certifications (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE volunteer_types ADD department_only BOOLEAN DEFAULT false NOT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE volunteer_type_contacts DROP CONSTRAINT FK_60FAC6F11BA493AB');
        $this->addSql('ALTER TABLE volunteer_type_certifications DROP CONSTRAINT FK_BA15F8981BA493AB');
        $this->addSql('ALTER TABLE volunteer_type_certifications DROP CONSTRAINT FK_BA15F898CB47068A');
        $this->addSql('DROP TABLE volunteer_type_contacts');
        $this->addSql('DROP TABLE volunteer_type_certifications');
        $this->addSql('ALTER TABLE volunteer_types DROP department_only');
    }
}
