<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260627104349 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Profile onboarding/SSO fields, user consents, consent texts and privacy notice';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE consent_texts (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(10) NOT NULL, header_title VARCHAR(255) NOT NULL, header_body TEXT NOT NULL, checkbox_label TEXT NOT NULL, footer TEXT NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_172A5C144180C698 ON consent_texts (locale)');
        $this->addSql('CREATE TABLE privacy_notices (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, event_name VARCHAR(255) NOT NULL, controller_org VARCHAR(255) NOT NULL, controller_email VARCHAR(255) NOT NULL, contact_email VARCHAR(255) NOT NULL, deletion_days INT NOT NULL, body_html TEXT NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE user_consents (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, data_processing BOOLEAN NOT NULL, full_name_visible BOOLEAN NOT NULL, email_visible BOOLEAN NOT NULL, phone_visible BOOLEAN NOT NULL, consent_locale VARCHAR(10) DEFAULT NULL, consented_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E6572967A76ED395 ON user_consents (user_id)');
        $this->addSql('ALTER TABLE user_consents ADD CONSTRAINT FK_E6572967A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE users ADD account_source VARCHAR(16) DEFAULT \'manual\' NOT NULL');
        $this->addSql('ALTER TABLE users ADD sso_user_id VARCHAR(128) DEFAULT NULL');
        $this->addSql('ALTER TABLE users ADD sso_provider VARCHAR(64) DEFAULT NULL');
        $this->addSql('ALTER TABLE users ADD onboarding_completed BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE users ADD onboarding_completed_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE users ADD unsubscribe_token VARCHAR(32) DEFAULT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E0674361 ON users (unsubscribe_token)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE user_consents DROP CONSTRAINT FK_E6572967A76ED395');
        $this->addSql('DROP TABLE consent_texts');
        $this->addSql('DROP TABLE privacy_notices');
        $this->addSql('DROP TABLE user_consents');
        $this->addSql('DROP INDEX UNIQ_1483A5E9E0674361');
        $this->addSql('ALTER TABLE users DROP account_source');
        $this->addSql('ALTER TABLE users DROP sso_user_id');
        $this->addSql('ALTER TABLE users DROP sso_provider');
        $this->addSql('ALTER TABLE users DROP onboarding_completed');
        $this->addSql('ALTER TABLE users DROP onboarding_completed_at');
        $this->addSql('ALTER TABLE users DROP unsubscribe_token');
    }
}
