<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * The security team's location check-in: the append-only log, the two privileges, and the Security
 * group.
 *
 * The group and privileges are seeded here as well as in the catalog, because a catalog preset only
 * reaches a database that is installed fresh and every existing event would otherwise have no way to
 * grant this to anybody.
 *
 * Nothing here touches the existing arrival flag on `states`. Venue entry and event arrival are
 * separate records on purpose.
 */
final class Version20260817103642 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Location check-in log, security privileges and the Security group';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE location_check_ins (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(16) NOT NULL, occurred_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, local_date DATE NOT NULL, overridden BOOLEAN NOT NULL, override_reason TEXT DEFAULT NULL, uuid UUID NOT NULL, user_id INT NOT NULL, actor_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_912A15A9D17F50A6 ON location_check_ins (uuid)');
        $this->addSql('CREATE INDEX IDX_912A15A9A76ED395 ON location_check_ins (user_id)');
        $this->addSql('CREATE INDEX IDX_912A15A910DAF24A ON location_check_ins (actor_id)');
        $this->addSql('CREATE INDEX idx_location_check_in_day ON location_check_ins (local_date)');
        $this->addSql('CREATE INDEX idx_location_check_in_user ON location_check_ins (user_id, local_date)');
        $this->addSql('ALTER TABLE location_check_ins ADD CONSTRAINT FK_912A15A9A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE location_check_ins ADD CONSTRAINT FK_912A15A910DAF24A FOREIGN KEY (actor_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');

        foreach (self::privileges() as $name => $description) {
            $this->addSql(
                'INSERT INTO privileges (name, description) SELECT :name, :description
                 WHERE NOT EXISTS (SELECT 1 FROM privileges WHERE name = :name)',
                ['name' => $name, 'description' => $description],
            );
        }

        $this->addSql(
            "INSERT INTO groups (name, slug, role, uuid) SELECT 'Security', 'security', 'ROLE_STAFF', gen_random_uuid()
             WHERE NOT EXISTS (SELECT 1 FROM groups WHERE slug = 'security')",
        );

        // The baseline privileges travel with the group: a staff group without news:view lands its
        // members on a 403 at the page sign-in sends them to.
        foreach (['security:checkin', 'backstage:view', 'user:locate', 'user:view', 'shift:view', 'manageshifts:view', 'news:view', 'faq:view', 'profile:view', 'worklog:self'] as $name) {
            $this->addSql(
                "INSERT INTO group_privileges (group_id, privilege_id)
                 SELECT g.id, p.id FROM groups g, privileges p
                 WHERE g.slug = 'security' AND p.name = :name
                   AND NOT EXISTS (SELECT 1 FROM group_privileges gp WHERE gp.group_id = g.id AND gp.privilege_id = p.id)",
                ['name' => $name],
            );
        }
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE location_check_ins DROP CONSTRAINT FK_912A15A9A76ED395');
        $this->addSql('ALTER TABLE location_check_ins DROP CONSTRAINT FK_912A15A910DAF24A');
        $this->addSql('DROP TABLE location_check_ins');

        $this->addSql("DELETE FROM group_privileges WHERE group_id IN (SELECT id FROM groups WHERE slug = 'security')");
        $this->addSql("DELETE FROM groups WHERE slug = 'security'");

        foreach (array_keys(self::privileges()) as $name) {
            $this->addSql('DELETE FROM group_privileges WHERE privilege_id IN (SELECT id FROM privileges WHERE name = :name)', ['name' => $name]);
            $this->addSql('DELETE FROM privileges WHERE name = :name', ['name' => $name]);
        }
    }

    /** @return array<string, string> */
    private static function privileges(): array
    {
        return [
            'security:checkin' => 'Check people in and out of the event location',
            'security:checkin:override' => 'Admit somebody the entry rules refuse, with a reason',
        ];
    }
}
