<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260525222926 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE duty_records (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, started_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, ended_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, auto_ended BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, user_id INT NOT NULL, department_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F1A15997A76ED395 ON duty_records (user_id)');
        $this->addSql('CREATE INDEX IDX_F1A15997AE80F5DF ON duty_records (department_id)');
        $this->addSql('CREATE TABLE internal_notes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, content TEXT NOT NULL, category VARCHAR(32) NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, author_id INT DEFAULT NULL, subject_user_id INT DEFAULT NULL, department_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D413D25D17F50A6 ON internal_notes (uuid)');
        $this->addSql('CREATE INDEX IDX_D413D25F675F31B ON internal_notes (author_id)');
        $this->addSql('CREATE INDEX IDX_D413D252EC7F37 ON internal_notes (subject_user_id)');
        $this->addSql('CREATE INDEX IDX_D413D25AE80F5DF ON internal_notes (department_id)');
        $this->addSql('ALTER TABLE duty_records ADD CONSTRAINT FK_F1A15997A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE duty_records ADD CONSTRAINT FK_F1A15997AE80F5DF FOREIGN KEY (department_id) REFERENCES departments (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE internal_notes ADD CONSTRAINT FK_D413D25F675F31B FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE internal_notes ADD CONSTRAINT FK_D413D252EC7F37 FOREIGN KEY (subject_user_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE internal_notes ADD CONSTRAINT FK_D413D25AE80F5DF FOREIGN KEY (department_id) REFERENCES departments (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE duty_records DROP CONSTRAINT FK_F1A15997A76ED395');
        $this->addSql('ALTER TABLE duty_records DROP CONSTRAINT FK_F1A15997AE80F5DF');
        $this->addSql('ALTER TABLE internal_notes DROP CONSTRAINT FK_D413D25F675F31B');
        $this->addSql('ALTER TABLE internal_notes DROP CONSTRAINT FK_D413D252EC7F37');
        $this->addSql('ALTER TABLE internal_notes DROP CONSTRAINT FK_D413D25AE80F5DF');
        $this->addSql('DROP TABLE duty_records');
        $this->addSql('DROP TABLE internal_notes');
    }
}
