<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260627092310 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Replace users_groups with scoped, time-boxed user_group_assignments; add group role and auto-increment group IDs';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE user_group_assignments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, expires_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, user_id INT NOT NULL, group_id INT NOT NULL, department_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_ED2DF437A76ED395 ON user_group_assignments (user_id)');
        $this->addSql('CREATE INDEX IDX_ED2DF437FE54D947 ON user_group_assignments (group_id)');
        $this->addSql('CREATE INDEX IDX_ED2DF437AE80F5DF ON user_group_assignments (department_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_group_department ON user_group_assignments (user_id, group_id, department_id)');
        $this->addSql('ALTER TABLE user_group_assignments ADD CONSTRAINT FK_ED2DF437A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_group_assignments ADD CONSTRAINT FK_ED2DF437FE54D947 FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_group_assignments ADD CONSTRAINT FK_ED2DF437AE80F5DF FOREIGN KEY (department_id) REFERENCES departments (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE users_groups DROP CONSTRAINT fk_ff8ab7e0a76ed395');
        $this->addSql('ALTER TABLE users_groups DROP CONSTRAINT fk_ff8ab7e0fe54d947');
        $this->addSql('DROP TABLE users_groups');
        $this->addSql('ALTER TABLE groups ADD role VARCHAR(32) DEFAULT NULL');
        $this->addSql('ALTER TABLE groups ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE users_groups (user_id INT NOT NULL, group_id INT NOT NULL, PRIMARY KEY (user_id, group_id))');
        $this->addSql('CREATE INDEX idx_ff8ab7e0fe54d947 ON users_groups (group_id)');
        $this->addSql('CREATE INDEX idx_ff8ab7e0a76ed395 ON users_groups (user_id)');
        $this->addSql('ALTER TABLE users_groups ADD CONSTRAINT fk_ff8ab7e0a76ed395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE users_groups ADD CONSTRAINT fk_ff8ab7e0fe54d947 FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_group_assignments DROP CONSTRAINT FK_ED2DF437A76ED395');
        $this->addSql('ALTER TABLE user_group_assignments DROP CONSTRAINT FK_ED2DF437FE54D947');
        $this->addSql('ALTER TABLE user_group_assignments DROP CONSTRAINT FK_ED2DF437AE80F5DF');
        $this->addSql('DROP TABLE user_group_assignments');
        $this->addSql('ALTER TABLE groups DROP role');
        $this->addSql('ALTER TABLE groups ALTER id DROP IDENTITY');
    }
}
