<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260627111846 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'GDPR: data exports, erasure requests and hashed banned identities';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE banned_identities (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, hash_type VARCHAR(16) NOT NULL, hash VARCHAR(64) NOT NULL, banned_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, appeal_requested_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_banned_hash ON banned_identities (hash)');
        $this->addSql('CREATE TABLE data_exports (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid VARCHAR(36) NOT NULL, status VARCHAR(16) NOT NULL, file_path VARCHAR(1024) DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, downloaded_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_882542B1D17F50A6 ON data_exports (uuid)');
        $this->addSql('CREATE INDEX IDX_882542B1A76ED395 ON data_exports (user_id)');
        $this->addSql('CREATE TABLE erasure_requests (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token VARCHAR(64) NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_89B05B915F37A13B ON erasure_requests (token)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_89B05B91A76ED395 ON erasure_requests (user_id)');
        $this->addSql('ALTER TABLE data_exports ADD CONSTRAINT FK_882542B1A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE erasure_requests ADD CONSTRAINT FK_89B05B91A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE data_exports DROP CONSTRAINT FK_882542B1A76ED395');
        $this->addSql('ALTER TABLE erasure_requests DROP CONSTRAINT FK_89B05B91A76ED395');
        $this->addSql('DROP TABLE banned_identities');
        $this->addSql('DROP TABLE data_exports');
        $this->addSql('DROP TABLE erasure_requests');
    }
}
