<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260804120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Shift groups: shifts that can only be applied to and cancelled together';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE shift_groups (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, name VARCHAR(128) NOT NULL, description TEXT DEFAULT NULL, department_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7CB5AB65D17F50A6 ON shift_groups (uuid)');
        $this->addSql('CREATE INDEX IDX_7CB5AB65AE80F5DF ON shift_groups (department_id)');
        $this->addSql('ALTER TABLE shift_groups ADD CONSTRAINT FK_SHIFT_GROUP_DEPARTMENT FOREIGN KEY (department_id) REFERENCES departments (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        // SET NULL, never CASCADE: deleting a group must ungroup its shifts, not delete them.
        $this->addSql('ALTER TABLE shifts ADD shift_group_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE shifts ADD CONSTRAINT FK_SHIFT_SHIFT_GROUP FOREIGN KEY (shift_group_id) REFERENCES shift_groups (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_1D1D712FD7E041E3 ON shifts (shift_group_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE shifts DROP CONSTRAINT FK_SHIFT_SHIFT_GROUP');
        $this->addSql('DROP INDEX IDX_1D1D712FD7E041E3');
        $this->addSql('ALTER TABLE shifts DROP shift_group_id');
        $this->addSql('DROP TABLE shift_groups');
    }
}
