<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260525203547 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE certifications (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, title VARCHAR(128) NOT NULL, description TEXT DEFAULT NULL, contact_person VARCHAR(128) DEFAULT NULL, contact_email VARCHAR(254) DEFAULT NULL, location VARCHAR(128) DEFAULT NULL, is_perpetual BOOLEAN NOT NULL, validity_period_days INT DEFAULT NULL, allow_self_confirmation BOOLEAN NOT NULL, staff_only BOOLEAN NOT NULL, is_active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3B0D76D5D17F50A6 ON certifications (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3B0D76D52B36786B ON certifications (title)');
        $this->addSql('CREATE TABLE departments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, name VARCHAR(128) NOT NULL, slug VARCHAR(128) NOT NULL, description TEXT DEFAULT NULL, staff_only BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_16AEB8D4D17F50A6 ON departments (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_16AEB8D45E237E06 ON departments (name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_16AEB8D4989D9B62 ON departments (slug)');
        $this->addSql('CREATE TABLE department_locations (department_id INT NOT NULL, location_id INT NOT NULL, PRIMARY KEY (department_id, location_id))');
        $this->addSql('CREATE INDEX IDX_CC643D76AE80F5DF ON department_locations (department_id)');
        $this->addSql('CREATE INDEX IDX_CC643D7664D218E ON department_locations (location_id)');
        $this->addSql('CREATE TABLE department_volunteer_types (department_id INT NOT NULL, volunteer_type_id INT NOT NULL, PRIMARY KEY (department_id, volunteer_type_id))');
        $this->addSql('CREATE INDEX IDX_800A12B3AE80F5DF ON department_volunteer_types (department_id)');
        $this->addSql('CREATE INDEX IDX_800A12B31BA493AB ON department_volunteer_types (volunteer_type_id)');
        $this->addSql('CREATE TABLE event_config (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, config_key VARCHAR(128) NOT NULL, value JSON DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E613582E95D1CAA6 ON event_config (config_key)');
        $this->addSql('CREATE TABLE locations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(128) NOT NULL, description TEXT DEFAULT NULL, map_url VARCHAR(255) DEFAULT NULL, phone VARCHAR(32) DEFAULT NULL, staff_only BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_17E64ABA5E237E06 ON locations (name)');
        $this->addSql('CREATE TABLE shift_types (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(128) NOT NULL, description TEXT DEFAULT NULL, staff_only BOOLEAN NOT NULL, department_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_52DE6F6E5E237E06 ON shift_types (name)');
        $this->addSql('CREATE INDEX IDX_52DE6F6EAE80F5DF ON shift_types (department_id)');
        $this->addSql('CREATE TABLE volunteer_types (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(128) NOT NULL, description TEXT DEFAULT NULL, contact_name VARCHAR(128) DEFAULT NULL, contact_phone VARCHAR(32) DEFAULT NULL, contact_email VARCHAR(254) DEFAULT NULL, restricted BOOLEAN NOT NULL, shift_self_signup BOOLEAN NOT NULL, show_on_dashboard BOOLEAN NOT NULL, hide_register BOOLEAN NOT NULL, hide_on_shift_view BOOLEAN NOT NULL, staff_only BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6B5E54C25E237E06 ON volunteer_types (name)');
        $this->addSql('ALTER TABLE department_locations ADD CONSTRAINT FK_CC643D76AE80F5DF FOREIGN KEY (department_id) REFERENCES departments (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE department_locations ADD CONSTRAINT FK_CC643D7664D218E FOREIGN KEY (location_id) REFERENCES locations (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE department_volunteer_types ADD CONSTRAINT FK_800A12B3AE80F5DF FOREIGN KEY (department_id) REFERENCES departments (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE department_volunteer_types ADD CONSTRAINT FK_800A12B31BA493AB FOREIGN KEY (volunteer_type_id) REFERENCES volunteer_types (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE shift_types ADD CONSTRAINT FK_52DE6F6EAE80F5DF FOREIGN KEY (department_id) REFERENCES departments (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE department_locations DROP CONSTRAINT FK_CC643D76AE80F5DF');
        $this->addSql('ALTER TABLE department_locations DROP CONSTRAINT FK_CC643D7664D218E');
        $this->addSql('ALTER TABLE department_volunteer_types DROP CONSTRAINT FK_800A12B3AE80F5DF');
        $this->addSql('ALTER TABLE department_volunteer_types DROP CONSTRAINT FK_800A12B31BA493AB');
        $this->addSql('ALTER TABLE shift_types DROP CONSTRAINT FK_52DE6F6EAE80F5DF');
        $this->addSql('DROP TABLE certifications');
        $this->addSql('DROP TABLE departments');
        $this->addSql('DROP TABLE department_locations');
        $this->addSql('DROP TABLE department_volunteer_types');
        $this->addSql('DROP TABLE event_config');
        $this->addSql('DROP TABLE locations');
        $this->addSql('DROP TABLE shift_types');
        $this->addSql('DROP TABLE volunteer_types');
    }
}
