<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260525211520 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE needed_volunteer_types (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, count INT NOT NULL, volunteer_type_id INT NOT NULL, shift_id INT DEFAULT NULL, location_id INT DEFAULT NULL, shift_type_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B0C805B91BA493AB ON needed_volunteer_types (volunteer_type_id)');
        $this->addSql('CREATE INDEX IDX_B0C805B9BB70BC0E ON needed_volunteer_types (shift_id)');
        $this->addSql('CREATE INDEX IDX_B0C805B964D218E ON needed_volunteer_types (location_id)');
        $this->addSql('CREATE INDEX IDX_B0C805B9A81DB0EA ON needed_volunteer_types (shift_type_id)');
        $this->addSql('CREATE TABLE shift_entries (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_comment TEXT DEFAULT NULL, noshow BOOLEAN NOT NULL, noshow_comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, shift_id INT NOT NULL, volunteer_type_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_40A98FBCBB70BC0E ON shift_entries (shift_id)');
        $this->addSql('CREATE INDEX IDX_40A98FBC1BA493AB ON shift_entries (volunteer_type_id)');
        $this->addSql('CREATE INDEX IDX_40A98FBCA76ED395 ON shift_entries (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_shift_user ON shift_entries (shift_id, user_id)');
        $this->addSql('CREATE TABLE shifts (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, url VARCHAR(255) DEFAULT NULL, starts_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ends_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, transaction_id UUID DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, shift_type_id INT DEFAULT NULL, location_id INT DEFAULT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1D1D712FA81DB0EA ON shifts (shift_type_id)');
        $this->addSql('CREATE INDEX IDX_1D1D712F64D218E ON shifts (location_id)');
        $this->addSql('CREATE INDEX IDX_1D1D712FDE12AB56 ON shifts (created_by)');
        $this->addSql('CREATE INDEX IDX_1D1D712F16FE72E1 ON shifts (updated_by)');
        $this->addSql('CREATE TABLE user_volunteer_types (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, supporter BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, volunteer_type_id INT NOT NULL, confirmed_by INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7982384DA76ED395 ON user_volunteer_types (user_id)');
        $this->addSql('CREATE INDEX IDX_7982384D1BA493AB ON user_volunteer_types (volunteer_type_id)');
        $this->addSql('CREATE INDEX IDX_7982384DFB3F81CB ON user_volunteer_types (confirmed_by)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_volunteer_type ON user_volunteer_types (user_id, volunteer_type_id)');
        $this->addSql('CREATE TABLE worklogs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, hours DOUBLE PRECISION NOT NULL, comment TEXT DEFAULT NULL, worked_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, creator_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C78A883AA76ED395 ON worklogs (user_id)');
        $this->addSql('CREATE INDEX IDX_C78A883A61220EA6 ON worklogs (creator_id)');
        $this->addSql('ALTER TABLE needed_volunteer_types ADD CONSTRAINT FK_B0C805B91BA493AB FOREIGN KEY (volunteer_type_id) REFERENCES volunteer_types (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE needed_volunteer_types ADD CONSTRAINT FK_B0C805B9BB70BC0E FOREIGN KEY (shift_id) REFERENCES shifts (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE needed_volunteer_types ADD CONSTRAINT FK_B0C805B964D218E FOREIGN KEY (location_id) REFERENCES locations (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE needed_volunteer_types ADD CONSTRAINT FK_B0C805B9A81DB0EA FOREIGN KEY (shift_type_id) REFERENCES shift_types (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE shift_entries ADD CONSTRAINT FK_40A98FBCBB70BC0E FOREIGN KEY (shift_id) REFERENCES shifts (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE shift_entries ADD CONSTRAINT FK_40A98FBC1BA493AB FOREIGN KEY (volunteer_type_id) REFERENCES volunteer_types (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE shift_entries ADD CONSTRAINT FK_40A98FBCA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE shifts ADD CONSTRAINT FK_1D1D712FA81DB0EA FOREIGN KEY (shift_type_id) REFERENCES shift_types (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE shifts ADD CONSTRAINT FK_1D1D712F64D218E FOREIGN KEY (location_id) REFERENCES locations (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE shifts ADD CONSTRAINT FK_1D1D712FDE12AB56 FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE shifts ADD CONSTRAINT FK_1D1D712F16FE72E1 FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_volunteer_types ADD CONSTRAINT FK_7982384DA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_volunteer_types ADD CONSTRAINT FK_7982384D1BA493AB FOREIGN KEY (volunteer_type_id) REFERENCES volunteer_types (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_volunteer_types ADD CONSTRAINT FK_7982384DFB3F81CB FOREIGN KEY (confirmed_by) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE worklogs ADD CONSTRAINT FK_C78A883AA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE worklogs ADD CONSTRAINT FK_C78A883A61220EA6 FOREIGN KEY (creator_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE needed_volunteer_types DROP CONSTRAINT FK_B0C805B91BA493AB');
        $this->addSql('ALTER TABLE needed_volunteer_types DROP CONSTRAINT FK_B0C805B9BB70BC0E');
        $this->addSql('ALTER TABLE needed_volunteer_types DROP CONSTRAINT FK_B0C805B964D218E');
        $this->addSql('ALTER TABLE needed_volunteer_types DROP CONSTRAINT FK_B0C805B9A81DB0EA');
        $this->addSql('ALTER TABLE shift_entries DROP CONSTRAINT FK_40A98FBCBB70BC0E');
        $this->addSql('ALTER TABLE shift_entries DROP CONSTRAINT FK_40A98FBC1BA493AB');
        $this->addSql('ALTER TABLE shift_entries DROP CONSTRAINT FK_40A98FBCA76ED395');
        $this->addSql('ALTER TABLE shifts DROP CONSTRAINT FK_1D1D712FA81DB0EA');
        $this->addSql('ALTER TABLE shifts DROP CONSTRAINT FK_1D1D712F64D218E');
        $this->addSql('ALTER TABLE shifts DROP CONSTRAINT FK_1D1D712FDE12AB56');
        $this->addSql('ALTER TABLE shifts DROP CONSTRAINT FK_1D1D712F16FE72E1');
        $this->addSql('ALTER TABLE user_volunteer_types DROP CONSTRAINT FK_7982384DA76ED395');
        $this->addSql('ALTER TABLE user_volunteer_types DROP CONSTRAINT FK_7982384D1BA493AB');
        $this->addSql('ALTER TABLE user_volunteer_types DROP CONSTRAINT FK_7982384DFB3F81CB');
        $this->addSql('ALTER TABLE worklogs DROP CONSTRAINT FK_C78A883AA76ED395');
        $this->addSql('ALTER TABLE worklogs DROP CONSTRAINT FK_C78A883A61220EA6');
        $this->addSql('DROP TABLE needed_volunteer_types');
        $this->addSql('DROP TABLE shift_entries');
        $this->addSql('DROP TABLE shifts');
        $this->addSql('DROP TABLE user_volunteer_types');
        $this->addSql('DROP TABLE worklogs');
    }
}
