<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260627102558 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Audit events (append-only), legal export records and the encrypted signing certificate';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE audit_events (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, event_id VARCHAR(64) NOT NULL, occurred_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, event_type VARCHAR(48) NOT NULL, action VARCHAR(48) NOT NULL, outcome VARCHAR(16) NOT NULL, actor_type VARCHAR(16) NOT NULL, actor_user_id INT DEFAULT NULL, actor_sso_id VARCHAR(128) DEFAULT NULL, actor_username VARCHAR(128) DEFAULT NULL, actor_role VARCHAR(32) DEFAULT NULL, actor_ip VARCHAR(64) DEFAULT NULL, actor_user_agent TEXT DEFAULT NULL, resource_type VARCHAR(64) DEFAULT NULL, resource_id VARCHAR(128) DEFAULT NULL, resource_owner_id VARCHAR(128) DEFAULT NULL, resource JSON NOT NULL, details JSON NOT NULL, session_id VARCHAR(128) DEFAULT NULL, request_url TEXT DEFAULT NULL, mfa_verified BOOLEAN NOT NULL, http_status INT DEFAULT NULL, error_message TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_70597B9171F7E88B ON audit_events (event_id)');
        $this->addSql('CREATE INDEX idx_audit_occurred_at ON audit_events (occurred_at)');
        $this->addSql('CREATE INDEX idx_audit_actor_user ON audit_events (actor_user_id)');
        $this->addSql('CREATE INDEX idx_audit_event_type ON audit_events (event_type)');
        $this->addSql('CREATE TABLE audit_exports (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid VARCHAR(36) NOT NULL, requested_by_user_id INT DEFAULT NULL, requested_by_username VARCHAR(128) NOT NULL, scope_start TIMESTAMP(0) WITH TIME ZONE NOT NULL, scope_end TIMESTAMP(0) WITH TIME ZONE NOT NULL, focus_user_id INT DEFAULT NULL, sha256 VARCHAR(64) NOT NULL, file_path VARCHAR(1024) NOT NULL, event_count INT NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, downloaded_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FD0CC130D17F50A6 ON audit_exports (uuid)');
        $this->addSql('CREATE TABLE signing_certificates (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, certificate_pem TEXT NOT NULL, private_key_pem TEXT NOT NULL, fingerprint VARCHAR(95) NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE audit_events');
        $this->addSql('DROP TABLE audit_exports');
        $this->addSql('DROP TABLE signing_certificates');
    }
}
