<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260712075249 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Advanced Matrix Planner positions model: position groups, named positions, per-shift positions and per-entry position assignments.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE named_positions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, display_order INT NOT NULL, capacity INT NOT NULL, self_applicable BOOLEAN NOT NULL, position_group_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8E658BBDA738BF0 ON named_positions (position_group_id)');
        $this->addSql('CREATE TABLE named_position_volunteer_types (named_position_id INT NOT NULL, volunteer_type_id INT NOT NULL, PRIMARY KEY (named_position_id, volunteer_type_id))');
        $this->addSql('CREATE INDEX IDX_9BB58822ECEF7E87 ON named_position_volunteer_types (named_position_id)');
        $this->addSql('CREATE INDEX IDX_9BB588221BA493AB ON named_position_volunteer_types (volunteer_type_id)');
        $this->addSql('CREATE TABLE named_position_certifications (named_position_id INT NOT NULL, certification_id INT NOT NULL, PRIMARY KEY (named_position_id, certification_id))');
        $this->addSql('CREATE INDEX IDX_DF42D245ECEF7E87 ON named_position_certifications (named_position_id)');
        $this->addSql('CREATE INDEX IDX_DF42D245CB47068A ON named_position_certifications (certification_id)');
        $this->addSql('CREATE TABLE position_groups (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, display_order INT NOT NULL, department_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_88357FDAE80F5DF ON position_groups (department_id)');
        $this->addSql('CREATE TABLE shift_position_assignments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, note TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, shift_entry_id INT NOT NULL, shift_position_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6C77B21C9382D1E6 ON shift_position_assignments (shift_entry_id)');
        $this->addSql('CREATE INDEX IDX_6C77B21C7661AC54 ON shift_position_assignments (shift_position_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_entry_position ON shift_position_assignments (shift_entry_id, shift_position_id)');
        $this->addSql('CREATE TABLE shift_positions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, required BOOLEAN NOT NULL, note TEXT DEFAULT NULL, shift_id INT NOT NULL, named_position_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_70D3615BB70BC0E ON shift_positions (shift_id)');
        $this->addSql('CREATE INDEX IDX_70D3615ECEF7E87 ON shift_positions (named_position_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_shift_position ON shift_positions (shift_id, named_position_id)');
        $this->addSql('ALTER TABLE named_positions ADD CONSTRAINT FK_8E658BBDA738BF0 FOREIGN KEY (position_group_id) REFERENCES position_groups (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE named_position_volunteer_types ADD CONSTRAINT FK_9BB58822ECEF7E87 FOREIGN KEY (named_position_id) REFERENCES named_positions (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE named_position_volunteer_types ADD CONSTRAINT FK_9BB588221BA493AB FOREIGN KEY (volunteer_type_id) REFERENCES volunteer_types (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE named_position_certifications ADD CONSTRAINT FK_DF42D245ECEF7E87 FOREIGN KEY (named_position_id) REFERENCES named_positions (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE named_position_certifications ADD CONSTRAINT FK_DF42D245CB47068A FOREIGN KEY (certification_id) REFERENCES certifications (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE position_groups ADD CONSTRAINT FK_88357FDAE80F5DF FOREIGN KEY (department_id) REFERENCES departments (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE shift_position_assignments ADD CONSTRAINT FK_6C77B21C9382D1E6 FOREIGN KEY (shift_entry_id) REFERENCES shift_entries (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE shift_position_assignments ADD CONSTRAINT FK_6C77B21C7661AC54 FOREIGN KEY (shift_position_id) REFERENCES shift_positions (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE shift_positions ADD CONSTRAINT FK_70D3615BB70BC0E FOREIGN KEY (shift_id) REFERENCES shifts (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE shift_positions ADD CONSTRAINT FK_70D3615ECEF7E87 FOREIGN KEY (named_position_id) REFERENCES named_positions (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE named_positions DROP CONSTRAINT FK_8E658BBDA738BF0');
        $this->addSql('ALTER TABLE named_position_volunteer_types DROP CONSTRAINT FK_9BB58822ECEF7E87');
        $this->addSql('ALTER TABLE named_position_volunteer_types DROP CONSTRAINT FK_9BB588221BA493AB');
        $this->addSql('ALTER TABLE named_position_certifications DROP CONSTRAINT FK_DF42D245ECEF7E87');
        $this->addSql('ALTER TABLE named_position_certifications DROP CONSTRAINT FK_DF42D245CB47068A');
        $this->addSql('ALTER TABLE position_groups DROP CONSTRAINT FK_88357FDAE80F5DF');
        $this->addSql('ALTER TABLE shift_position_assignments DROP CONSTRAINT FK_6C77B21C9382D1E6');
        $this->addSql('ALTER TABLE shift_position_assignments DROP CONSTRAINT FK_6C77B21C7661AC54');
        $this->addSql('ALTER TABLE shift_positions DROP CONSTRAINT FK_70D3615BB70BC0E');
        $this->addSql('ALTER TABLE shift_positions DROP CONSTRAINT FK_70D3615ECEF7E87');
        $this->addSql('DROP TABLE named_positions');
        $this->addSql('DROP TABLE named_position_volunteer_types');
        $this->addSql('DROP TABLE named_position_certifications');
        $this->addSql('DROP TABLE position_groups');
        $this->addSql('DROP TABLE shift_position_assignments');
        $this->addSql('DROP TABLE shift_positions');
    }
}
