<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260712102041 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Department request/invitation links: request_links.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE request_links (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token VARCHAR(64) NOT NULL, type VARCHAR(32) NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, revoked_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, department_id INT NOT NULL, created_by INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8C951D3D5F37A13B ON request_links (token)');
        $this->addSql('CREATE INDEX IDX_8C951D3DAE80F5DF ON request_links (department_id)');
        $this->addSql('CREATE INDEX IDX_8C951D3DDE12AB56 ON request_links (created_by)');
        $this->addSql('ALTER TABLE request_links ADD CONSTRAINT FK_8C951D3DAE80F5DF FOREIGN KEY (department_id) REFERENCES departments (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE request_links ADD CONSTRAINT FK_8C951D3DDE12AB56 FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE request_links DROP CONSTRAINT FK_8C951D3DAE80F5DF');
        $this->addSql('ALTER TABLE request_links DROP CONSTRAINT FK_8C951D3DDE12AB56');
        $this->addSql('DROP TABLE request_links');
    }
}
