<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260627113422 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'SSO group mappings and their join tables';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE sso_group_mappings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sso_group_id VARCHAR(64) NOT NULL, name VARCHAR(128) NOT NULL, slug VARCHAR(128) NOT NULL, staff_only BOOLEAN NOT NULL, department_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D0C0A82359B076ED ON sso_group_mappings (sso_group_id)');
        $this->addSql('CREATE INDEX IDX_D0C0A823AE80F5DF ON sso_group_mappings (department_id)');
        $this->addSql('CREATE TABLE sso_mapping_groups (sso_group_mapping_id INT NOT NULL, group_id INT NOT NULL, PRIMARY KEY (sso_group_mapping_id, group_id))');
        $this->addSql('CREATE INDEX IDX_DB042C8FE8CA54AF ON sso_mapping_groups (sso_group_mapping_id)');
        $this->addSql('CREATE INDEX IDX_DB042C8FFE54D947 ON sso_mapping_groups (group_id)');
        $this->addSql('CREATE TABLE sso_mapping_volunteer_types (sso_group_mapping_id INT NOT NULL, volunteer_type_id INT NOT NULL, PRIMARY KEY (sso_group_mapping_id, volunteer_type_id))');
        $this->addSql('CREATE INDEX IDX_650F9B05E8CA54AF ON sso_mapping_volunteer_types (sso_group_mapping_id)');
        $this->addSql('CREATE INDEX IDX_650F9B051BA493AB ON sso_mapping_volunteer_types (volunteer_type_id)');
        $this->addSql('CREATE TABLE sso_mapping_badges (sso_group_mapping_id INT NOT NULL, badge_id INT NOT NULL, PRIMARY KEY (sso_group_mapping_id, badge_id))');
        $this->addSql('CREATE INDEX IDX_539F4665E8CA54AF ON sso_mapping_badges (sso_group_mapping_id)');
        $this->addSql('CREATE INDEX IDX_539F4665F7A2C2FC ON sso_mapping_badges (badge_id)');
        $this->addSql('ALTER TABLE sso_group_mappings ADD CONSTRAINT FK_D0C0A823AE80F5DF FOREIGN KEY (department_id) REFERENCES departments (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sso_mapping_groups ADD CONSTRAINT FK_DB042C8FE8CA54AF FOREIGN KEY (sso_group_mapping_id) REFERENCES sso_group_mappings (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sso_mapping_groups ADD CONSTRAINT FK_DB042C8FFE54D947 FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sso_mapping_volunteer_types ADD CONSTRAINT FK_650F9B05E8CA54AF FOREIGN KEY (sso_group_mapping_id) REFERENCES sso_group_mappings (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sso_mapping_volunteer_types ADD CONSTRAINT FK_650F9B051BA493AB FOREIGN KEY (volunteer_type_id) REFERENCES volunteer_types (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sso_mapping_badges ADD CONSTRAINT FK_539F4665E8CA54AF FOREIGN KEY (sso_group_mapping_id) REFERENCES sso_group_mappings (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sso_mapping_badges ADD CONSTRAINT FK_539F4665F7A2C2FC FOREIGN KEY (badge_id) REFERENCES badges (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE sso_group_mappings DROP CONSTRAINT FK_D0C0A823AE80F5DF');
        $this->addSql('ALTER TABLE sso_mapping_groups DROP CONSTRAINT FK_DB042C8FE8CA54AF');
        $this->addSql('ALTER TABLE sso_mapping_groups DROP CONSTRAINT FK_DB042C8FFE54D947');
        $this->addSql('ALTER TABLE sso_mapping_volunteer_types DROP CONSTRAINT FK_650F9B05E8CA54AF');
        $this->addSql('ALTER TABLE sso_mapping_volunteer_types DROP CONSTRAINT FK_650F9B051BA493AB');
        $this->addSql('ALTER TABLE sso_mapping_badges DROP CONSTRAINT FK_539F4665E8CA54AF');
        $this->addSql('ALTER TABLE sso_mapping_badges DROP CONSTRAINT FK_539F4665F7A2C2FC');
        $this->addSql('DROP TABLE sso_group_mappings');
        $this->addSql('DROP TABLE sso_mapping_groups');
        $this->addSql('DROP TABLE sso_mapping_volunteer_types');
        $this->addSql('DROP TABLE sso_mapping_badges');
    }
}
