<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260712122729 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Global Call for Help: help_calls, help_call_responses.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE help_call_responses (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(8) NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, call_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9398962850A89B2C ON help_call_responses (call_id)');
        $this->addSql('CREATE INDEX IDX_93989628A76ED395 ON help_call_responses (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_call_user ON help_call_responses (call_id, user_id)');
        $this->addSql('CREATE TABLE help_calls (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slots_requested INT NOT NULL, slots_filled INT NOT NULL, status VARCHAR(16) NOT NULL, version INT DEFAULT 1 NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, shift_id INT NOT NULL, created_by INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BD3B9C76BB70BC0E ON help_calls (shift_id)');
        $this->addSql('CREATE INDEX IDX_BD3B9C76DE12AB56 ON help_calls (created_by)');
        $this->addSql('ALTER TABLE help_call_responses ADD CONSTRAINT FK_9398962850A89B2C FOREIGN KEY (call_id) REFERENCES help_calls (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE help_call_responses ADD CONSTRAINT FK_93989628A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE help_calls ADD CONSTRAINT FK_BD3B9C76BB70BC0E FOREIGN KEY (shift_id) REFERENCES shifts (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE help_calls ADD CONSTRAINT FK_BD3B9C76DE12AB56 FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE help_call_responses DROP CONSTRAINT FK_9398962850A89B2C');
        $this->addSql('ALTER TABLE help_call_responses DROP CONSTRAINT FK_93989628A76ED395');
        $this->addSql('ALTER TABLE help_calls DROP CONSTRAINT FK_BD3B9C76BB70BC0E');
        $this->addSql('ALTER TABLE help_calls DROP CONSTRAINT FK_BD3B9C76DE12AB56');
        $this->addSql('DROP TABLE help_call_responses');
        $this->addSql('DROP TABLE help_calls');
    }
}
